# -*- coding: utf-8 -*-
"""StableDiffusionUI-Voldemort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iy-xW9t1-OQWhb0hNxueGij8phCyluOh

Adapted from: https://colab.research.google.com/drive/1AfAmwLMd_Vx33O9IwY2TmO9wKZ8ABRRa
"""

!nvidia-smi

import os
os.kill(os.getpid(), 9) # This will crash Colab (required, everything will still be intact so dont worry)

"""Clone webui repository"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
# %cd stable-diffusion-webui

"""Install requirements, download repositories of stable diffusion"""

!pip install -r requirements.txt
!mkdir repositories
!git clone https://github.com/CompVis/stable-diffusion.git repositories/stable-diffusion
!git clone https://github.com/CompVis/taming-transformers.git repositories/taming-transformers
!git clone https://github.com/sczhou/CodeFormer.git repositories/CodeFormer
!git clone https://github.com/salesforce/BLIP.git repositories/BLIP
!pip install -r repositories/CodeFormer/requirements.txt

"""Download the model from huggingface. See link at the start for different ways."""

#@title Normal 1.4 model
# get a token from https://huggingface.co/settings/tokens
user_token = "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" #@param {type:"string"}
user_header = f"\"Authorization: Bearer {user_token}\""
!wget --header={user_header} https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt -O model.ckpt

"""Downlad GFPGAN model."""

!wget https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth

"""Kill the runtime."""

import os
os.kill(os.getpid(), 9) # This will crash Colab (required, everything will still be intact so dont worry)

!ls -la /content/stable-diffusion-webui/model.ckpt

"""Change into Web UI directory and download updates"""

# Commented out IPython magic to ensure Python compatibility.
# %cd stable-diffusion-webui
!git pull

"""Launch web ui. You will get a link to nnn.gradio.app, follow it."""

import sys
sys.argv = ['webui.py', "--share", "--opt-split-attention"]

import webui
webui.webui()